[package]
name = "catalyst-chain-syncer"
version = "0.1.0"
edition = "2021"

[dependencies]
cardano-immutabledb-reader = { workspace = true }
catalyst-chaindata-writer = { workspace = true }
db-util = { workspace = true }

clap = { version = "4.5.4", default-features = false, features = ["derive", "help", "usage", "std"] }
memory-stats = "1.1.0"
pallas-traverse = "0.25.0"
parse-size = "1.0.0"
tokio = { workspace = true, default-features = false, features = ["rt-multi-thread", "macros", "signal", "sync"] }
