[package]
name = "cardano-immutabledb-reader"
version = "0.1.0"
edition = "2021"

[dependencies]
binary-layout = "4.0.2"
pallas-traverse = "0.25.0"
tokio = { workspace = true, features = ["fs", "io-util", "sync", "rt"] }

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "rt"] }
